<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title', 'LiVCCI Report')</title>
    <style>
        @page { margin: 24px 28px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111827; }
        .header-wrap { border-bottom: 2px solid #1D2A68; padding-bottom: 10px; margin-bottom: 14px; }
        .header-table { width: 100%; border-collapse: collapse; }
        .logo-cell { width: 90px; vertical-align: top; }
        .title-cell { vertical-align: top; }
        .logo { width: 72px; height: auto; }
        .org { font-size: 16px; font-weight: bold; color: #1D2A68; }
        .addr { font-size: 10px; color: #374151; margin-top: 2px; }
        .report-title { font-size: 14px; font-weight: bold; color: #1D2A68; margin-top: 8px; }
        .meta { font-size: 10px; color: #6b7280; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #d1d5db; padding: 7px; text-align: left; vertical-align: top; }
        th { background: #1D2A68; color: #ffffff; font-size: 10px; text-transform: uppercase; }
        .summary th { background: #1876C3; }
        .footer { margin-top: 26px; font-size: 10px; color: #374151; }
        .signature-line { margin-top: 24px; border-top: 1px solid #9ca3af; width: 240px; padding-top: 5px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header-wrap">
        <table class="header-table">
            <tr>
                <td class="logo-cell">
                    @php
                        $logoPath = public_path('images/logo.png');
                    @endphp
                    @if(file_exists($logoPath))
                        <img class="logo" src="{{ $logoPath }}" alt="LiVCCI Logo">
                    @endif
                </td>
                <td class="title-cell">
                    <div class="org">Livingstone Chamber of Commerce and Industry (LiVCCI)</div>
                    <div class="addr">PO Box 4037, Livingstone</div>
                    <div class="report-title">@yield('report_title')</div>
                    <div class="meta">Generated On: {{ $generatedAt->format('Y-m-d H:i:s') }}</div>
                </td>
            </tr>
        </table>
    </div>

    @yield('content')

    <div class="footer">
        <div>Generated By: Secretariat Reporting System ({{ $generatedAt->format('Y-m-d H:i:s') }})</div>
        <div class="signature-line">Authorized By Secretariat</div>
    </div>
</body>
</html>
