export const INDUSTRY_ACTIVITIES = {
    'Tourism & Hospitality': [
        'Lodges & Hotels',
        'Guest Houses',
        'Tour Operators',
        'Travel Agencies',
        'Restaurants & Cafes',
        'Wildlife & Safari',
        'Car Hire',
        'Curio & Souvenirs',
        'Event Management',
        'Camping & Outdoor',
        'Conference & MICE Services',
        'Boat Cruises & River Safaris',
        'Adventure Sports & Activities',
        'Hospitality Training Services',
        'Transport Shuttles',
        'Destination Marketing',
        'Catering Services',
        'Tour Guiding Services',
    ],
    'Trade & Commerce': [
        'Retailers',
        'Wholesalers',
        'Cross-border Trade',
        'Distribution',
        'E-commerce',
        'Hardware Stores',
        'Auto Spares',
        'Boutiques & Fashion',
        'Butcheries',
        'Supermarkets',
        'Pharmacies & Medical Supplies',
        'FMCG Distribution',
        'Office Supplies & Equipment',
        'Import & Export Services',
        'General Merchants',
        'Electronics & Appliances',
        'Fuel & Energy Retail',
        'Cold Chain Distribution',
    ],
    'Financial Services': [
        'Commercial Banks',
        'Micro-finance',
        'Insurance Brokers',
        'Mobile Money Services',
        'Accounting & Audit',
        'Tax Consultancy',
        'Legal Services',
        'Real Estate Agencies',
        'Investment Advisory',
        'Pension & Benefits Services',
        'Foreign Exchange Services',
        'Fintech Solutions',
        'Savings & Credit Services',
        'Loan Recovery & Collections',
        'Business Valuation Services',
        'Risk & Compliance Advisory',
    ],
    'Construction & Engineering': [
        'Civil Engineering',
        'Building Contractors',
        'Electrical Installations',
        'Plumbing & Sanitation',
        'Architectural Design',
        'Quantity Surveying',
        'Land Surveying',
        'Metal Fabrication',
        'Road Works & Infrastructure',
        'HVAC Installation & Maintenance',
        'Project Management Services',
        'Water & Borehole Engineering',
        'Welding Services',
        'Building Materials Supply',
        'Renovation & Interior Fit-Out',
        'Structural Engineering',
    ],
    'Agriculture & Manufacturing': [
        'Commercial Farming',
        'Agro-Dealers',
        'Livestock & Poultry',
        'Food Processing',
        'Beverage Production',
        'Textiles & Garments',
        'Milling',
        'Furniture Manufacturing',
        'Irrigation Services',
        'Seed Production',
        'Dairy Processing',
        'Packaging & Labeling',
        'Agro-Logistics',
        'Feed Production',
        'Leather & Footwear Manufacturing',
        'Industrial Processing',
    ],
    'IT & Creative Media': [
        'Software Development',
        'IT Support & Networking',
        'Graphic Design',
        'Photography & Video',
        'Digital Marketing',
        'Printing & Stationery',
        'Computer Sales',
        'Telecommunications',
        'Cybersecurity Services',
        'Web & App Hosting',
        'UI/UX Design',
        'Animation & Motion Graphics',
        'Brand Strategy',
        'Social Media Management',
        'Content Production',
        'Data Analytics Services',
    ],
    'Cooperatives & Social Enterprise': [
        'Multi-purpose Cooperatives',
        'Artisan & Wood Carvers',
        'NGOs',
        'Community Based Org (CBO)',
        'Credit Unions',
        'Agricultural Cooperatives',
        'Youth & Women Groups',
        'Skills Training Programs',
        'Community Health Initiatives',
        'Recycling & Green Enterprise',
        'Village Savings Groups',
        'Fair Trade Initiatives',
        'Craft & Cultural Enterprises',
        'Social Impact Consulting',
        'Advocacy & Outreach Programs',
    ],
};
