export const INDUSTRY_ACTIVITIES = {
    'Tourism & Hospitality': [
        'Lodges & Hotels',
        'Guest Houses',
        'Tour Operators',
        'Travel Agencies',
        'Restaurants & Cafes',
        'Wildlife & Safari',
        'Car Hire',
        'Curio & Souvenirs',
        'Event Management',
        'Camping & Outdoor',
    ],
    'Trade & Commerce': [
        'Retailers',
        'Wholesalers',
        'Cross-border Trade',
        'Distribution',
        'E-commerce',
        'Hardware Stores',
        'Auto Spares',
        'Boutiques & Fashion',
        'Butcheries',
        'Supermarkets',
    ],
    'Financial Services': [
        'Commercial Banks',
        'Micro-finance',
        'Insurance Brokers',
        'Mobile Money Services',
        'Accounting & Audit',
        'Tax Consultancy',
        'Legal Services',
        'Real Estate Agencies',
    ],
    'Construction & Engineering': [
        'Civil Engineering',
        'Building Contractors',
        'Electrical Installations',
        'Plumbing & Sanitation',
        'Architectural Design',
        'Quantity Surveying',
        'Land Surveying',
        'Metal Fabrication',
    ],
    'Agriculture & Manufacturing': [
        'Commercial Farming',
        'Agro-Dealers',
        'Livestock & Poultry',
        'Food Processing',
        'Beverage Production',
        'Textiles & Garments',
        'Milling',
        'Furniture Manufacturing',
    ],
    'IT & Creative Media': [
        'Software Development',
        'IT Support & Networking',
        'Graphic Design',
        'Photography & Video',
        'Digital Marketing',
        'Printing & Stationery',
        'Computer Sales',
        'Telecommunications',
    ],
    'Cooperatives & Social Enterprise': [
        'Multi-purpose Cooperatives',
        'Artisan & Wood Carvers',
        'NGOs',
        'Community Based Org (CBO)',
        'Credit Unions',
        'Agricultural Cooperatives',
        'Youth & Women Groups',
    ],
};
